### PR TITLE
Switch to setuptools

### PR DESCRIPTION
**Pull request by yetanotherion**
Switch to setuptools

### CODE REVIEW

**Comment by david-cortes** [comment]
Thanks for the change, but I’d first want to ask: does `distutils` generate some undesired behavior? I understand there are some differences such as where they put non-Python files or such, but for a package like this that does not have anything special, is there any difference? Doesn’t a `pip` install end up anyway using `setuptools`?
Also, given that `setuptools` is not part of standard Python and that it can throw errors in situations in which distutils works fine, could you make a fallback mechanism? e.g.
```python
try:
    from setuptools …
except:
    from distutils …
```

**Comment by yetanotherion** [comment]
> does `distutils` generate some undesired behavior?

I was not able to generate a wheel with `distutils`.

> could you make a fallback mechanism?

That's a good idea. Still are you ok to support both `setuptools` and `distutils`?

**Comment by david-cortes** [comment]
Fair enough, didn’t envision building wheels for the package. Please proceed then with switching it to `setuptools` with a fallback to `distutils`.

**Comment by yetanotherion** [comment]
Thanks!

**Pull request merged**
